### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by maziggy** [tomvandeneede/p2pp#94]
I'm using the Master branch under MacOS 11.1 and get the following error:

Post-processing script tools/p2pp/p2pp_dist/p2pp.command on file Downloads/p2pp/foo.prusa.mcf.gcode failed.
Error code: 1
Output:
Traceback (most recent call last):
File "tools/p2pp/p2pp_dist/P2PP.py", line 146, in <module>
main(vars(arguments.parse_args()))
File "tools/p2pp/p2pp_dist/P2PP.py", line 87, in main
mcf.generate(v.filename,
File "tools/p2pp/p2pp_dist/p2pp/mcf.py", line 961, in generate
gcode_parseline(process_line_count)
File "tools/p2pp/p2pp_dist/p2pp/mcf.py", line 570, in gcode_parseline
if not coordinate_on_bed(_x, _y):
File "tools/p2pp/p2pp_dist/p2pp/mcf.py", line 178, in coordinate_on_bed
return x_on_bed(x) and y_on_bed(y)
File "tools/p2pp/p2pp_dist/p2pp/mcf.py", line 174, in x_on_bed
return inrange(x, v.bed_origin_x, v.bed_origin_x + v.bed_size_x)
File "tools/p2pp/p2pp_dist/p2pp/mcf.py", line 166, in inrange
return low <= number <= high
TypeError: '<=' not supported between instances of 'float' and 'str'

GCODE file is attached.

Thanks!
[gcode.zip](https://github.com/tomvandeneede/p2pp/files/5893827/gcode.zip)

**Comment by maziggy** [comment]
In the meantime I've found out that the start GCODE line:

M557 X29:316 Y14:310 S20:20  ; mesh grid dummy

is parsed and the string in question is '29:316'.

**Comment by tomvandeneede** [comment]
What pronter is this for?

**Comment by maziggy** [comment]
A BLV mgn Cube with 330x330 bed.

**Comment by tomvandeneede** [comment]
to my knowledge the dev version should will solve this

**Comment by maziggy** [comment]
It does ;) Thanks!
